### ISSUE TITLE
mdEditor v0.5.0 updates

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdEditor-doc#2]
- [ ] Updates to timePeriod: adiwg/mdEditor#223, adiwg/mdEditor#139
- [ ] New date settings: adiwg/mdEditor#139
- [ ] FGDC CSDGM import: adiwg/mdEditor#223
